global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'control-plane'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['control-plane:8090']

  - job_name: 'sample-client'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['sample-client:8081']
